name: oneapi-test-apt

on:
  push: {}
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'

env:
  LINUX_COMPONENTS: intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic,intel-oneapi-compiler-fortran
  PRAGMA_KEYS: akamai-x-get-cache-key, akamai-x-cache-on, akamai-x-cache-remote-on, akamai-x-get-true-cache-key, akamai-x-check-cacheable, akamai-x-get-request-id, akamai-x-serial-no, akamai-x-get-ssl-client-session-id, X-Akamai-CacheTrack, akamai-x-get-client-ip, akamai-x-feo-trace, akamai-x-tapioca-trace

jobs:
  build_linux_apt:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: dig akamai DNS
      run: dig apt.repos.intel.com +short
    - name: install whois
      run: sudo apt-get install -y whois
    - name: dig akamai DNS with city grabbing
      run: |
        export ip_=$(dig apt.repos.intel.com +short | tail -n1)
        whois $ip_ | grep -iE ^country:
        whois $ip_ | grep -iE ^city:
    - name: download test file with pragma keys
      run: |
        curl -D -  -o /dev/null  -H "Pragma: $PRAGMA_KEYS" https://apt.repos.intel.com/test.txt 
  build_linux_apt2:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: dig akamai DNS
      run: dig apt.repos.intel.com +short
    - name: install whois
      run: sudo apt-get install -y whois
    - name: dig akamai DNS with city grabbing
      run: |
        export ip_=$(dig apt.repos.intel.com +short | tail -n1)
        whois $ip_ | grep -iE ^country:
        whois $ip_ | grep -iE ^city:
    - name: download test file with pragma keys
      run: |
        curl -D -  -o /dev/null  -H "Pragma: $PRAGMA_KEYS" https://apt.repos.intel.com/test.txt 
  build_linux_apt3:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: dig akamai DNS
      run: dig apt.repos.intel.com +short
    - name: install whois
      run: sudo apt-get install -y whois
    - name: dig akamai DNS with city grabbing
      run: |
        export ip_=$(dig apt.repos.intel.com +short | tail -n1)
        whois $ip_ | grep -iE ^country:
        whois $ip_ | grep -iE ^city:
    - name: download test file with pragma keys
      run: |
        curl -D -  -o /dev/null  -H "Pragma: $PRAGMA_KEYS" https://apt.repos.intel.com/test.txt 
